### clerk controller

GET  /ecommerce-rest-api/api/v1/clerks HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###

GET  /ecommerce-rest-api/api/v1/clerks/7 HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###

DELETE   /ecommerce-rest-api/api/v1/clerks/8 HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###

POST  /ecommerce-rest-api/api/v1/clerks HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

{
    "email": "heshamdd@gmail.com",
    "hireDate": "2022-04-11T21:10:15.038Z[UTC]",
    "name": "hesham",
    "password": 1234
}

############################Product endpoint######################################

GET /ecommerce-rest-api/api/v1/products
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###

GET /ecommerce-rest-api/api/v1/products/1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###

POST  /ecommerce-rest-api/api/v1/products HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

{
    "name": "prod",
    "price": 50,
    "desc": "desc",
    "stock": 50,
    "categories": ["CAT1"]
}

###
PUT  /ecommerce-rest-api/api/v1/products HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "prod",
  "price": 60000,
  "desc": "desc",
  "stock": 5000
}

###

DELETE   /ecommerce-rest-api/api/v1/products/11 HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###
GET  /ecommerce-rest-api/api/v1/products/1/categories HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json


###
PUT  /ecommerce-rest-api/api/v1/products/1/categories HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

["CAT1", "CAT2", "CAT4"]
####################################Categories#################################################

GET  /ecommerce-rest-api/api/v1/categories/CAT4/products HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###

GET  /ecommerce-rest-api/api/v1/categories HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

#########################################################################################3

###
GET  /ecommerce-api/api/v1/orders HTTP/1.1
Host: localhost:9090
Accept: application/json
Content-Type: application/json

###



###

GET  /ecommerce-api/api/v1/customers/5 HTTP/1.1
Host: localhost:9090
Accept: jets/media

###

POST /ecommerce-api/api/v1/customers HTTP/1.1
Host:localhost:9090
Content-Type: jets/media

CustomerEntity [address=address, email=email, name=name 
                ,password=password]